SELECT id_empleado ,nombre,apellido FROM empleados WHERE estado=1;

//***
INSERT INTO `detalle_planilla` (`id_detalle`, `id_planilla`, `id_empleado`, `sueldo_base`, `sueldo_extraordinario`, `total_devengado`, `total_descuento`, `total_liquido`, `estado`) VALUES (NULL, '1', '1', '5000', '51515', '555', '5255', '123', '1');
/**

SELECT empleados.id_empleado, empleados.nombre, empleados.apellido, conceptos.fecha_inicio, conceptos.fecha_fin ,conceptos.monto,conceptos.debe_Haber FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado

SELECT empleados.id_empleado, empleados.nombre, empleados.apellido,empleados.id_puesto,empleados.id_area, conceptos.fecha_inicio, conceptos.fecha_fin ,conceptos.monto,conceptos.debe_Haber FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado AND empleados.id_empleado=1;

 INNER JOIN tipo_comisiones
  ON comisiones.id_tipo_comisiones = tipo_comisiones.id_tipo_comisiones;

SELECT empleados.id_empleado, empleados.nombre, empleados.apellido,empleados.id_puesto,area.nombre, conceptos.fecha_inicio, conceptos.fecha_fin ,conceptos.monto,conceptos.debe_Haber FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado INNER JOIN area ON area.id_area = empleados.id_area 



SELECT empleados.id_empleado, empleados.nombre, empleados.apellido,puestos.id_sueldo,area.nombre, conceptos.fecha_inicio, conceptos.fecha_fin ,conceptos.monto,conceptos.debe_Haber FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado INNER JOIN area ON area.id_area = empleados.id_area INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto 





//**
SELECT empleados.id_empleado, empleados.nombre, empleados.apellido,sueldos.salario,area.nombre, conceptos.fecha_inicio, conceptos.fecha_fin ,conceptos.monto,conceptos.debe_Haber FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado INNER JOIN area ON area.id_area = empleados.id_area INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto INNER JOIN sueldos ON sueldos.id_sueldo = puestos.id_sueldo





SELECT tipo_comisiones.nombre, tipo_comisiones.valor FROM empleados INNER JOIN comisiones ON empleados.id_empleado = comisiones.id_empleado INNER JOIN tipo_comisiones ON comisiones.id_tipo_comisiones = tipo_comisiones.id_tipo_comisiones AND empleados.id_empleado =1;





/***/ sql ideas

SELECT count(*) FROM empleados WHERE estado= 1 contar cuantos registros hay 

SELECT id_empleado FROM empleados WHERE estado= 1

SELECT empleados.id_empleado, empleados.nombre, empleados.apellido,sueldos.salario,area.nombre FROM empleados INNER JOIN area ON area.id_area = empleados.id_area INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto INNER JOIN sueldos ON sueldos.id_sueldo = puestos.id_sueldo // datos principales de clientes 
SELECT sueldos.salario FROM empleados INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto INNER JOIN sueldos ON sueldos.id_sueldo = puestos.id_sueldo WHERE empleados.id_empleado =1

SELECT empleados.id_empleado, empleados.nombre, empleados.apellido, conceptos.fecha_inicio, conceptos.fecha_fin ,conceptos.monto,conceptos.debe_Haber FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado // optencion de los conceptos


SELECT tipo_comisiones.nombre, tipo_comisiones.valor FROM empleados INNER JOIN comisiones ON empleados.id_empleado = comisiones.id_empleado INNER JOIN tipo_comisiones ON comisiones.id_tipo_comisiones = tipo_comisiones.id_tipo_comisiones AND empleados.id_empleado =1; //optener comiciones 


SELECT sueldos.salario FROM empleados INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto INNER JOIN sueldos ON sueldos.id_sueldo = puestos.id_sueldo WHERE empleados.id_empleado =1 // sueldo 
SELECT round( sum(horas.costo * horas.cantidad *((SELECT sueldos.salario FROM empleados INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto INNER JOIN sueldos ON sueldos.id_sueldo = puestos.id_sueldo WHERE empleados.id_empleado =1)/160)),2)AS horas FROM horas WHERE id_empleado =1 //sueldo horas extra
SELECT round( sum(horas.costo * horas.cantidad *((SELECT sueldos.salario FROM empleados INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto INNER JOIN sueldos ON sueldos.id_sueldo = puestos.id_sueldo WHERE empleados.id_empleado =1)/160)),2)+ (SELECT sueldos.salario FROM empleados INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto INNER JOIN sueldos ON sueldos.id_sueldo = puestos.id_sueldo WHERE empleados.id_empleado =1)AS horas FROM horas WHERE id_empleado =1 sueldo extraordiario


SELECT conceptos.monto FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" // optener bonificaciones y sueldo
SELECT SUM(conceptos.monto) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" //******x


SELECT conceptos.monto FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" descuentos
SELECT round( sum(conceptos.monto),2) as monto FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" or conceptos.fecha_fin >"2020-04-30" or fecha_inicio ="1111-11-11" or fecha_fin ="1111-11-11" //total des



SELECT conceptos.monto FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" UNION SELECT conceptos.monto FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio = "1111-11-11" AND conceptos.fecha_fin = "1111-11-11" UNION SELECT conceptos.monto FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_fin >= "2020-04-30"
select ((SELECT sum(conceptos.monto) AS mont1 FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30") + (SELECT sum(conceptos.monto) AS mont1 FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" )+(SELECT sum(conceptos.monto) AS mont1 FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" )) AS total suma de 3 o mas variables
select ((SELECT sum(conceptos.monto) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" ) + (SELECT sum(conceptos.monto) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_inicio = "1111-11-11" AND conceptos.fecha_fin = "1111-11-11")+( SELECT sum(conceptos.monto) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_fin >= "2020-04-30")) AS total

select ((SELECT COALESCE (sum(conceptos.monto),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" ) + (SELECT COALESCE (sum(conceptos.monto),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio = "1111-11-11" AND conceptos.fecha_fin = "1111-11-11")+(SELECT COALESCE (sum(conceptos.monto),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_fin > "2020-04-30")) AS total //ya consige los calores de los conseptos 

select ((SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" ) + (SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio = "1111-11-11" AND conceptos.fecha_fin = "1111-11-11")+(SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_fin > "2020-04-30")) AS total //bine conceptos 

select ((SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" ) + (SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio = "1111-11-11" AND conceptos.fecha_fin = "1111-11-11")+(SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_fin > "2020-04-30")+ COALESCE((SELECT sueldos.salario FROM empleados INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto INNER JOIN sueldos ON sueldos.id_sueldo = puestos.id_sueldo WHERE empleados.id_empleado =1),0)) AS total // sueldo devengado

select ((SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" ) + (SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_inicio = "1111-11-11" AND conceptos.fecha_fin = "1111-11-11")+(SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_fin > "2020-04-30")) AS total //total descuento

select ((SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" ) + (SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio = "1111-11-11" AND conceptos.fecha_fin = "1111-11-11")+(SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_fin > "2020-04-30")+ COALESCE((SELECT sueldos.salario FROM empleados INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto INNER JOIN sueldos ON sueldos.id_sueldo = puestos.id_sueldo WHERE empleados.id_empleado =1),0))- ((SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" ) + (SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_inicio = "1111-11-11" AND conceptos.fecha_fin = "1111-11-11")+(SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_fin > "2020-04-30"))  AS total // total liquido
select COALESCE (((SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" ) + (SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_inicio = "1111-11-11" AND conceptos.fecha_fin = "1111-11-11")+(SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =1 AND conceptos.fecha_fin > "2020-04-30")+ COALESCE((SELECT sueldos.salario FROM empleados INNER JOIN puestos ON puestos.id_puesto = empleados.id_puesto INNER JOIN sueldos ON sueldos.id_sueldo = puestos.id_sueldo WHERE empleados.id_empleado =1),0)),0)-COALESCE (((SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_inicio >= "2020-04-01" AND conceptos.fecha_fin <= "2020-04-30" ) + (SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_inicio = "1111-11-11" AND conceptos.fecha_fin = "1111-11-11")+(SELECT COALESCE (round(sum(conceptos.monto),2),0) FROM empleados INNER JOIN conceptos ON empleados.id_empleado = conceptos.id_empleado WHERE empleados.id_empleado =1 AND conceptos.estado =1 AND conceptos.debe_Haber =0 AND conceptos.fecha_fin > "2020-04-30")),0)  AS total total liquido /**/

 